spring:
  application:
    name: inventory-service
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: inventory
server:
  port: 9005
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
