spring:
  application:
    name: basket-service
  redis:
    host: ${REDIS_HOST}
    port: 6379
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER}
    consumer:
      bootstrap-servers: ${KAFKA_SERVER}
      group-id: add-cart
      properties:
        spring:
          deserializer:
            key:
              trusted:
                packages: "*"
            value:
              trusted:
                packages: "*"
server:
  port: 9004
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    preferIpAddress: true
