spring:
  application:
    name: basket-service
  redis:
    host: localhost
    port: 6379
server:
  port: 9004
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
