spring:
  application:
    name: book-service
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${SQL_HOST}:1433;databaseName=books;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8;
    username: sa
    password: ${SQL_PASS}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER}
    consumer:
      boostrap-servers: ${KAFKA_SERVER}
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus