spring:
  application:
    name: book-service
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost\MSI:1433;databaseName=books;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8;
    username: sa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
