scrape_configs:
  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['order-service:9007']
        labels:
          application: 'My order service'
      - targets: [ 'user-service:9003' ]
        labels:
          application: 'My user service'
      - targets: [ 'email-service:9009' ]
        labels:
          application: 'My email service'
      - targets: [ 'book-service:9001' ]
        labels:
          application: 'My book service'
      - targets: [ 'basket-service:9004' ]
        labels:
          application: 'My basket service'
      - targets: [ 'server:8761' ]
        labels:
          application: 'My server'
      - targets: [ 'inventory-service:9005' ]
        labels:
          application: 'My inventory service'