spring:
  application:
    name: email-service
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: 'localhost:9092'
    consumer:
      boostrap-servers: 'localhost:9092'
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${emailuser}
    password: ${emailpass}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 9009
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
