spring:
  application:
    name: user-service
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${SQL_HOST}:1433;databaseName=accounts;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8;
    username: sa
    password: ${SQL_PASS}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9003
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    preferIpAddress: true
security:
  jwt:
    token:
      secret-key:
        secrt-value: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus