spring:
  application:
    name: order-service
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost\MSI:1433;databaseName=orders;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8;
    username: sa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: 'localhost:9092'
    consumer:
      boostrap-servers: 'localhost:9092'
server:
  port: 9007
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
